### ISSUE TITLE
Add Camila's info on DublinCSS relaunch post

### ISSUE THREAD

**Issue by sheldonled** [dublincss/dublincss.github.io#3]
### User Story

**AS** any DublinCSS website visitor
**WHEN** I visit https://dublincss.github.io/dublincss-relaunch
**I SHOULD** see Camila's and her talk's info on the page

### Actions
@camilawaz to provide 
- Description for the talk: **CSS and Illustrations**
- Bio

**Comment by camilawaz** [comment]
**TALK DESCRIPTION:**
CSS and Illustrations
There is a thousand ways you can make writing CSS fun. One of those is turning code into images - to be more accurate, illustrations! 
In this talk, we will explore a few techniques and how to get started with CSS Illustrations. 


**BIO:** 

Camila Waz is a Brazilian web designer and developer, now based in Dublin - Ireland. 

Her passion for content brought her into the world of tech where she got to know Front End Technologies and Design by building blog themes. 
Using this knowledge she worked as a Freelancer for a number of years helping entrepreneurs and bloggers to get their message (and their websites!) out there. At the same time, she contributed to her local tech community organizing events, meetups and training sessions for new developers.  

Now she works as a UI/UX Web Developer and is a co-organiser for DublinCSS a community with monthly meetups that welcomes all developers, designers and curious individuals, regardless of experience level, to discuss and learn about the latest and standard CSS tips and techniques.

**Comment by osmarpetry** [comment]
I'm working on this!

**Comment by osmarpetry** [comment]
Is done in #17 PR
